import { readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

const VIRTUAL_ID = 'virtual:team-logos';
const RESOLVED_ID = `\0${VIRTUAL_ID}`;
const SUPPORTED_EXTS = ['svg', 'png', 'jpg', 'jpeg', 'webp'] as const;

type Variant = 'light' | 'dark';

type DiscoveredLogo = {
	number: number;
	light?: string;
	dark?: string;
};

function isSupportedExt(ext: string): boolean {
	return (SUPPORTED_EXTS as readonly string[]).includes(ext);
}

function parseTeamNumber(name: string): number {
	if (!/^[1-9]\d*$/.test(name)) {
		throw new RangeError(`Invalid team number: ${JSON.stringify(name)}`);
	}
	return Number(name);
}

function ensureUnique(team: number, variant: Variant, current: string | undefined, next: string): string {
	if (current !== undefined) {
		throw new Error(
			`Team ${team} has multiple ${variant} variants (${current} and ${next}). Only one file per variant is allowed.`,
		);
	}
	return next;
}

function discoverLogos(logosDir: string): DiscoveredLogo[] {
	const byNumber = new Map<number, DiscoveredLogo>();

	let entries: string[];
	try {
		entries = readdirSync(logosDir);
	} catch {
		return [];
	}

	for (const entry of entries) {
		if (entry.startsWith('.')) continue;
		const fullPath = path.join(logosDir, entry);
		const stat = statSync(fullPath);

		if (stat.isFile()) {
			const dot = entry.lastIndexOf('.');
			if (dot <= 0) continue;
			const stem = entry.slice(0, dot);
			const ext = entry.slice(dot + 1).toLowerCase();
			if (!isSupportedExt(ext)) continue;
			const number = parseTeamNumber(stem);
			const existing = byNumber.get(number);
			if (existing && (existing.light !== undefined || existing.dark !== undefined)) {
				throw new Error(
					`Team ${number} has both a top-level file (${entry}) and a variant directory. Use one or the other.`,
				);
			}
			byNumber.set(number, { number, light: entry, dark: entry });
			continue;
		}

		if (!stat.isDirectory()) continue;

		const number = parseTeamNumber(entry);
		const existing = byNumber.get(number);
		if (existing) {
			throw new Error(
				`Team ${number} has both a top-level file and a variant directory (${entry}/). Use one or the other.`,
			);
		}

		const logo: DiscoveredLogo = { number };
		const dirEntries = readdirSync(fullPath);
		for (const child of dirEntries) {
			if (child.startsWith('.')) continue;
			const childPath = path.join(fullPath, child);
			if (!statSync(childPath).isFile()) {
				throw new Error(`Unexpected nested directory: public/logos/${entry}/${child}`);
			}
			const dot = child.lastIndexOf('.');
			if (dot <= 0) {
				throw new Error(`Variant file missing extension: public/logos/${entry}/${child}`);
			}
			const stem = child.slice(0, dot).toLowerCase();
			const ext = child.slice(dot + 1).toLowerCase();
			if (!isSupportedExt(ext)) {
				throw new Error(`Unsupported variant extension: public/logos/${entry}/${child}`);
			}
			if (stem !== 'light' && stem !== 'dark') {
				throw new Error(`Variant file must be named light.<ext> or dark.<ext>: public/logos/${entry}/${child}`);
			}
			const rel = `${entry}/${child}`;
			if (stem === 'light') {
				logo.light = ensureUnique(number, 'light', logo.light, rel);
			} else {
				logo.dark = ensureUnique(number, 'dark', logo.dark, rel);
			}
		}

		if (logo.light === undefined && logo.dark === undefined) {
			throw new Error(`Team ${number} directory has no light or dark variant.`);
		}

		byNumber.set(number, logo);
	}

	return [...byNumber.values()].sort((a, b) => a.number - b.number);
}

function renderModule(logos: readonly DiscoveredLogo[]): string {
	const entries = logos
		.map((logo) => {
			const parts: string[] = [`number: ${logo.number}`];
			if (logo.light !== undefined) parts.push(`light: ${JSON.stringify(logo.light)}`);
			if (logo.dark !== undefined) parts.push(`dark: ${JSON.stringify(logo.dark)}`);
			return `\t{ ${parts.join(', ')} },`;
		})
		.join('\n');

	return `// Generated by logos-plugin. Do not edit.\nexport const TEAM_LOGOS = Object.freeze([\n${entries}\n]);\n`;
}

export function teamLogosPlugin(): Plugin {
	let logosDir = '';

	return {
		name: 'logos-frc-sh:team-logos',
		enforce: 'pre',
		configResolved(config) {
			logosDir = path.resolve(config.publicDir || path.join(config.root, 'public'), 'logos');
		},
		resolveId(id) {
			if (id === VIRTUAL_ID) return RESOLVED_ID;
			return null;
		},
		load(id) {
			if (id !== RESOLVED_ID) return null;
			const logos = discoverLogos(logosDir);
			return renderModule(logos);
		},
		configureServer(server) {
			server.watcher.add(logosDir);
			const invalidate = (changed: string) => {
				if (!changed.startsWith(logosDir)) return;
				const mod = server.moduleGraph.getModuleById(RESOLVED_ID);
				if (mod) {
					server.moduleGraph.invalidateModule(mod);
					server.ws.send({ type: 'full-reload' });
				}
			};
			server.watcher.on('add', invalidate);
			server.watcher.on('unlink', invalidate);
			server.watcher.on('addDir', invalidate);
			server.watcher.on('unlinkDir', invalidate);
		},
	};
}
